AoxiangRobotWeb/urls.py
from django.urls import path, include
from dashboard.views import *

urlpatterns = [
    path('', include('dashboard.urls')),
    path('ax/', include('aoxiang.urls')),
    path('ch/', include('codehub.urls')),
    path('blog/', include('blog.urls'))

]

handler404 = e404
handler500 = e500
handler403 = e403
handler400 = e400

blog/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.urls import path
import blog.views as view
import blog.apis as api

urlpatterns = [
    path('', view.index, name='blog_index'),
    path('login', view.login, name='blog_login'),
    # path('register', register, name='blog_register'),

    path('active', api.verify, name='blog_api_verify'),
    path('api/login', api.login, name='blog_api_login'),
    path('api/register', api.register, name='blog_api_register'),
    path('api/logout', api.logout, name='blog_api_logout')
]

codehub/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.urls import path
from codehub.views import *

urlpatterns = [
    path('', paste, name='ch_paste'),
    path('l', list_all, name='ch_list'),
    path('p/<str:codeid>', codeview, name='ch_cv'),
    path('p/<str:codeid>/raw', coderaw, name='ch_raw'),
    path('d/<str:codeid>', delete, name='ch_d'),
    path('auth', authorization, name='ch_auth')
]

codehub/models.py
from django.db import models
import uuid


def generate_uuid():
    return uuid.uuid4().hex


class Code(models.Model):
    id = models.CharField(primary_key=True, default=generate_uuid, editable=False, max_length=40)
    LANGUAGE = [
        'auto',
        'plaintext',
        'apache',
        'bash',
        'c#',
        'c++',
        'css',
        'coffeescript',
        'diff',
        'html',
        'xml',
        'http',
        'ini',
        'toml',
        'json',
        'java',
        'javascript',
        'makefile',
        'markdown',
        'nginx',
        'objective-c',
        'php',
        'perl',
        'properties',
        'python',
        'ruby',
        'sql',
        'shell',
        'session'
    ]

    author = models.CharField(max_length=30)
    language = models.CharField(max_length=10)
    code = models.TextField(default='')
    paste_time = models.DateTimeField(auto_now=True)

    password = models.TextField(null=True, default=None)

    def __str__(self):
        return '{} {} ({})'.format(self.id, self.author, self.language)

codehub/views.py
from django.shortcuts import get_object_or_404, render, redirect
from codehub.models import *
from dashboard.apis import *
from django.http import HttpResponseRedirect


def list_all(request):
    page = request.GET.get('p')
    author = request.GET.get('a')
    if page == '' or page is None:
        page = 0
    if author is None:
        author = ''
    try:
        page = int(page)
    except ValueError:
        page = 0

    codes = Code.objects.filter(author__icontains=author).order_by('-paste_time')[page * 100:(page + 1) * 100]

    return render(request, 'CodeHub/list.html', {
        'codes': codes
    })


def paste(request):
    author = request.POST.get('author')
    language = request.POST.get('language')
    code_text = request.POST.get('code')
    password = request.POST.get('password')
    password = '' if password is None else password

    if language is None or language.lower() not in Code.LANGUAGE:
        return render(request, 'CodeHub/paste.html')

    if code_text is None or code_text.strip('\n') == '':
        return render(request, 'CodeHub/paste.html', {
            'err_code': 'Your code can not be empty!',
        })
    # save info
    code = Code()
    code.author = 'anonymous' if author is None or author == '' else author
    code.language = language.lower()
    code.language = '' if code.language == 'auto' else code.language
    code.code = code_text.strip('\n') + '\n'
    if password == '':
        code.password = ''
    else:
        code.password = password_hash(password)
    code.save()

    response = redirect(codeview, codeid=code.id)
    if password != '':
        response.set_cookie(key=code.id, value=code.password)
    return response


def coderaw(request, codeid):
    password = request.COOKIES.get(codeid)
    password = '' if password is None else password

    code = get_object_or_404(Code, id=codeid)

    if code.password == password:
        return render(request, 'CodeHub/RawView.html', {'code': code})
    else:
        return authorization(request, codeid)


def codeview(request, codeid):
    password = request.COOKIES.get(codeid)
    password = '' if password is None else password

    code = get_object_or_404(Code, id=codeid)

    if code.password == password:
        return render(request, 'CodeHub/CodeView.html', {
            'code': code,
            'remove': '' if password == '' else '1'
        })
    else:
        return authorization(request, codeid)


def delete(request, codeid):
    password = request.COOKIES.get(codeid)
    password = '' if password is None else password

    code = get_object_or_404(Code, id=codeid)

    if code.password == password:
        resp = redirect(list_all)
        if code.password != '':
            code.delete()
            resp.delete_cookie(codeid)
        return redirect(list_all)
    else:
        return authorization(request, codeid)


def authorization(request, codeid):
    password = request.COOKIES.get(codeid)
    password = '' if password is None else password

    code = get_object_or_404(Code, id=codeid)

    if code.password == password:
        resp = HttpResponseRedirect(request.path_info)
        if password != '':
            resp.set_cookie(key=codeid, value=password)
        return resp

    password = request.POST.get('password')
    password = '' if password is None else password
    if password != '':
        password = password_hash(password)

    if code.password == password:
        resp = HttpResponseRedirect(request.path_info)
        if password != '':
            resp.set_cookie(key=codeid, value=password)
        return resp

    return render(request, 'CodeHub/auth.html')

codehub/templates/CodeHub/CodeView.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}
    View -- CodeHub
{% endblock %}

{% block user_section %}
{% endblock %}

{% block ext_header %}
    <style>
        @font-face {
            font-family: "DSM";
            src: url("{% static 'dashboard/static/custom/font/DejaVuSansMono.ttf' %}");
        }

        code, code pre {
            font-size: 16px;
            font-family: DSM;
            overflow-x: visible;
            line-height: 20px;
        }

        table {
            border-spacing: 12px 0;
        }

        th {
            text-align: right;
            padding-right: 6px;
            border-right: 2px solid darkgrey;
        }
    </style>

    <link rel="stylesheet" type="text/css" href="{% static 'CodeHub/css/github.css' %}">
    <script src="{% static 'CodeHub/js/highlight.pack.js' %}"></script>
    <script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

{% block ext_js %}
    <script src="{% static 'CodeHub/js/lineNumbers2.js' %}"></script>
    <script>
        $('#code_delete_cancel').click(function () {
            $('#remove_code').click()
        });
        $('#code_delete_confirm').click(function () {
            location.replace('{% url 'ch_d' code.id %}')
        });
    </script>
{% endblock %}


{% block content %}
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <a href="{% url 'ch_list' %}?a={{ code.author }}" class="m-link m--font-boldest">
                            {{ code.author|title }}
                        </a>
                        <small>
                            pasted at {{ code.paste_time|date:"Y-m-d H:i:s" }}
                            <a href="{% url 'ch_raw' code.id %}" class="m-link m--font-bold">
                                <i> raw </i>
                            </a>
                        </small>
                    </h3>
                </div>
            </div>

            <div class="m-portlet__head-tools">
                <ul class="m-portlet__nav">
                    <li class="m-portlet__nav-item">
                        <div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push"
                             m-dropdown-toggle="hover" aria-expanded="true">
                            <a href="#"
                               class="m-portlet__nav-link btn btn-lg btn-secondary  m-btn m-btn--icon m-btn--icon-only m-btn--pill  m-dropdown__toggle">
                                <i class="la la-ellipsis-h m--font-brand"></i>
                            </a>
                            <div class="m-dropdown__wrapper" style="z-index: 101;">
                                <span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"
                                      style="left: auto; right: 21.5px;"></span>
                                <div class="m-dropdown__inner">
                                    <div class="m-dropdown__body">
                                        <div class="m-dropdown__content">
                                            <ul class="m-nav">
                                                <li class="m-nav__section m-nav__section--first">
                                                    <span class="m-nav__section-text">
                                                        Quick Actions
                                                    </span>
                                                </li>
                                                <li class="m-nav__item">
                                                    <a href="{% url 'ch_list' %}" class="m-nav__link">
                                                        <i class="m-nav__link-icon flaticon-list-1"></i>
                                                        <span class="m-nav__link-text">
                                                            Index
                                                        </span>
                                                    </a>
                                                </li>
                                                <li class="m-nav__item">
                                                    <a href="{% url 'ch_paste' %}" class="m-nav__link">
                                                        <i class="m-nav__link-icon flaticon-file"></i>
                                                        <span class="m-nav__link-text">
                                                            Paste Another
                                                        </span>
                                                    </a>
                                                </li>
                                                {% if remove != '' %}
                                                <li class="m-nav__item">
                                                    <a href="#" class="m-nav__link" id="remove_code" data-toggle="modal" data-target="#m_modal_5">
                                                        <i class="m-nav__link-icon flaticon-delete-1"></i>
                                                        <span class="m-nav__link-text">
                                                            Remove
                                                        </span>
                                                    </a>
                                                </li>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="m-portlet__body blk">
            <pre><code class="{{ code.language }}" id="code"
                       style="background-color: white;">{{ code.code }}</code></pre>
            {{ code.get_language_display }}
        </div>
    </div>
    <div class="modal fade" id="m_modal_5" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content" style="border-radius: 30px">
                <div class="m-alert m-alert--icon alert alert-warning" role="alert" style="margin: 0; border-radius: 20px">
                    <div class="m-alert__icon">
                        <i class="flaticon-danger"></i>
                    </div>
                    <div class="m-alert__text">
                        <strong> WARNING!! &nbsp; Confirm ?</strong><br>
                        <div class="m-alert__actions" style="width: 200px;">
                            <button type="button" class="btn btn-danger btn-sm m-btn m-btn--pill m-btn--wide" id="code_delete_confirm" style="margin-right: 15px">
                                Yes
                            </button>
                            <button type="button" class="btn btn-accent btn-sm m-btn m-btn--pill m-btn--wide" id="code_delete_cancel">
                                No
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

codehub/templates/CodeHub/RawView.html
<html lang="en_us">
<head>
    <title>Raw View -- CodeHub</title>
</head>
<body>
<pre style="word-wrap: break-word; white-space: pre-wrap;">
{{ code.code }}
</pre>
</body>
</html>

codehub/templates/CodeHub/auth.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}
    View -- CodeHub
{% endblock %}

{% block user_section %}
{% endblock %}

{% block ext_header %}
    <style>
        @font-face {
            font-family: "DSM";
            src: url("{% static 'dashboard/static/custom/font/DejaVuSansMono.ttf' %}");
        }

        code, code pre {
            font-size: 16px;
            font-family: DSM;
            overflow-x: visible;
            line-height: 20px;
        }

        table {
            border-spacing: 12px 0;
        }

        th {
            text-align: right;
            padding-right: 6px;
            border-right: 2px solid darkgrey;
        }
    </style>
{% endblock %}

{% block ext_js %}
<script>
    $(document).ready(function () {
        $('#input_disp').click();
    });
</script>
{% endblock %}


{% block content %}
    <button type="button" data-toggle="modal" data-target="#m_modal_5" style="display: none;" id="input_disp">
        Launch Modal
    </button>

    <div class="modal fade" id="m_modal_5" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        Authorization Required
                    </h5>
                </div>
                <form method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                            <div class="form-group">
                                <label for="recipient-name" class="form-control-label">
                                    Password
                                </label>
                                <input type="password" class="form-control" id="password" placeholder="password" name="password">
                            </div>
                    </div>
                    <div class="modal-footer" style="padding: 13px;">
                        <button type="submit" class="btn btn-primary">
                            Submit!
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

codehub/templates/CodeHub/list.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}
    List All -- CodeHub
{% endblock %}

{% block user_section %}
{% endblock %}

{% block ext_header %}
    <style>
        @font-face {
            font-family: "DSM";
            src: url("{% static 'dashboard/static/custom/font/DejaVuSansMono.ttf' %}");
        }

        span.ch-text {
            {#font-size: 16px !important;#}
            font-family: DSM;
            overflow-x: visible;
            {#line-height: 20px;#}
        }
    </style>
{% endblock %}

{% block ext_js %}
{% endblock %}

{% block content %}
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <a class="m-link m--font-boldest" href="{% url 'ch_list' %}">
                            Index
                        </a>
                        <small>
                            All The Code is Here
                        </small>
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div class="m-section__content">
                <div class="m-list-timeline">
                    <div class="m-list-timeline__items">
                        <div class="m-list-timeline__item">
                            <span class="m-list-timeline__badge m-list-timeline__badge--accent"></span>
                            <span class="m-list-timeline__text ch-text">
                                <a href="{% url 'ch_paste' %}" class="m-link m--font-boldest">
                                    <i class="fa flaticon-add m--font-brand"></i>
                                </a>
                            </span>
                            <span class="m-list-timeline__time"> {{ code.paste_time|date:"Y-m-d H:i:s" }}</span>
                        </div>
                        {% for code in codes %}
                            <div class="m-list-timeline__item">
                                <span class="m-list-timeline__badge m-list-timeline__badge--accent"></span>
                                <span class="m-list-timeline__text ch-text">
                                    <a href="{% url 'ch_cv' code.id %}" class="m-link m--font-bold">
                                        {{ code.author|title }}
                                    </a>
                                    {% if code.language != '' %}
                                        <small>
                                            {{ code.language }}
                                        </small>
                                    {% else %}
                                        <small>
                                            auto
                                        </small>
                                    {% endif %}
                                </span>
                                <span class="m-list-timeline__time"> {{ code.paste_time|date:"Y-m-d H:i:s" }}</span>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

codehub/templates/CodeHub/paste.html
{% extends 'dashboard/base.html' %}

{% load static %}

{% block title %}
    Paste -- CodeHub
{% endblock %}

{% block user_section %}
{% endblock %}

{% block ext_js %}
    <script>
        $('#submit-btn').click(function () {
            $('#submit-btn').css('pointer-events', 'none');
        });
    </script>
{% endblock %}

{% block ext_header %}
{% endblock %}

{% block content %}
    {% if err_code != '' and err_code is not None %}
        <div class="alert alert-danger alert-dismissible fade show   m-alert m-alert--air" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
            <strong>
                Error !!!
            </strong>
            {{ err_code }}
        </div>
    {% endif %}
    <div class="m-portlet m-portlet--tab">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon m--hide">
                        <i class="la la-gear"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        Paste &amp; Share Your Code
                        <small>
                            <a href="{% url 'ch_list' %}" class="m-link m--font-bold">
                                <i>
                                    Index
                                </i>
                            </a>
                        </small>
                    </h3>
                </div>
            </div>
        </div>
        <form class="m-form m-form--fit m-form--label-align-right" action="{% url 'ch_paste' %}" method="POST">
            {% csrf_token %}
            <div class="m-portlet__body">
                <div class="form-group m-form__group">
                    <label>
                        Author Name
                    </label>
                    <input name="author" class="form-control m-input m-input--solid" placeholder="Author Name" maxlength="30" autocomplete="off">
                    <span class="m-form__help">
                        30 char max, default: anonymous
                    </span>
                </div>
                <div class="form-group m-form__group">
                    <label for="exampleSelect1">
                        Language
                    </label>
                    <select class="form-control m-input m-input--solid" name="language">
                        <option value="auto"> auto detected</option>
                        <option value="plaintext">plaintext</option>
                        <option value="Apache">Apache</option>
                        <option value="Bash">Bash</option>
                        <option value="C#">C#</option>
                        <option value="C++">C++</option>
                        <option value="CSS">CSS</option>
                        <option value="CoffeeScript">CoffeeScript</option>
                        <option value="Diff">Diff</option>
                        <option value="HTML">HTML</option>
                        <option value="XML">XML</option>
                        <option value="HTTP">HTTP</option>
                        <option value="Ini">Ini</option>
                        <option value="TOML">TOML</option>
                        <option value="JSON">JSON</option>
                        <option value="Java">Java</option>
                        <option value="JavaScript">JavaScript</option>
                        <option value="Makefile">Makefile</option>
                        <option value="Markdown">Markdown</option>
                        <option value="Nginx">Nginx</option>
                        <option value="Objective-C">Objective-C</option>
                        <option value="PHP">PHP</option>
                        <option value="Perl">Perl</option>
                        <option value="Properties">Properties</option>
                        <option value="Python">Python</option>
                        <option value="Ruby">Ruby</option>
                        <option value="SQL">SQL</option>
                        <option value="Shell">Shell</option>
                        <option value="Session">Session</option>
                    </select>
                </div>
                <div class="form-group m-form__group">
                    <label for="exampleTextarea">
                        Code
                    </label>
                    <textarea name='code' class="form-control m-input m-input--solid" rows="20"></textarea>
                </div>
            </div>
            <div class="form-group m-form__group">
                <label>
                    Password
                </label>
                <input name="password" class="form-control m-input m-input--solid" placeholder="Password" maxlength="30" type="password" autocomplete="new-password">
                <span class="m-form__help">
                    Leave blank to allow access by everyone
                </span>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <button type="submit" class="btn btn-success" id="submit-btn">
                        Submit
                    </button>
                    <button type="reset" class="btn btn-secondary">
                        Reset
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}